### ISSUE TITLE
Encrypted private key

### ISSUE THREAD

**Issue by lukasvan3l** [andruschka/pm2-meteor#10]
I'm getting this issue, can it be fixed in your code or am I doing something weird?

```
/usr/local/lib/node_modules/pm2-meteor/node_modules/nodemiral/node_modules/ssh2/lib/client.js:161
        throw new Error('Encrypted private key detected, but no passphrase giv
              ^
Error: Encrypted private key detected, but no passphrase given
    at Client.connect (/usr/local/lib/node_modules/pm2-meteor/node_modules/nodemiral/node_modules/ssh2/lib/client.js:161:15)
    at SSH.connect (/usr/local/lib/node_modules/pm2-meteor/node_modules/nodemiral/lib/ssh.js:12:16)
    at Session._withSshClient (/usr/local/lib/node_modules/pm2-meteor/node_modules/nodemiral/lib/session.js:58:12)
    at Session.execute (/usr/local/lib/node_modules/pm2-meteor/node_modules/nodemiral/lib/session.js:140:8)
    at Object.module.exports.checkDeps (/usr/local/lib/node_modules/pm2-meteor/lib/remoteTasks.js:34:22)
    at /usr/local/lib/node_modules/pm2-meteor/lib/commandList.js:36:30
    at /usr/local/lib/node_modules/pm2-meteor/node_modules/async/lib/async.js:713:13
    at iterate (/usr/local/lib/node_modules/pm2-meteor/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/pm2-meteor/node_modules/async/lib/async.js:281:9)
    at _parallel (/usr/local/lib/node_modules/pm2-meteor/node_modules/async/lib/async.js:712:9)
```

**Comment by andruschka** [comment]
Could you maybe post your pm2-meteor.json (make sure that you replace your passwords with something else ;) )

**Comment by lukasvan3l** [comment]
Thanks for looking into this!

```
{
  "appName": "myApp",
  "appLocation": {
    "local": "."
  },
  "meteorSettingsLocation": "settings.json",
  "prebuildScript": "",
  "meteorBuildFlags": "--architecture os.linux.x86_64",
  "env": {
    "ROOT_URL": "http://myapp.q42.com",
    "PORT": 80,
    "MONGO_URL": "mongodb://xxx/myapp",
    "TZ": "Europe/Amsterdam",
  },
  "server": {
    "host": "x.x.x.x",
    "username": "lukas",
    "pem":"~/.ssh/id_rsa",
    "deploymentDir": "/opt/pm2-meteor",
    "exec_mode": "fork_mode",
    "instances": 1
  }
}
```

**Comment by andruschka** [comment]
Ok your settings file looks good. Seems that you have an encrypted private key and need a passphrase ?! You could cat your id_rsa and if it begins with Proc-Type: ... it is encrypted
, in the meantime I will add support for private keys and passphrases ...

**Comment by andruschka** [comment]
Ok i found the problem. If your id_rsa is passphrase protected you should be able to deal with it like this: [arunodas solution](https://github.com/arunoda/meteor-up#ssh-keys-with-passphrase-or-ssh-agent-support)

**Comment by ffxsam** [comment]
That doesn't work. I have my id_rsa in the agent:

    2048 SHA256:4Ev1tjg/q8zoyu4f/JvI+yq2m3u6OM9OeeP/G8b8Zso /Users/samh/.ssh/id_rsa (RSA)

Yet when I run `pm2-meteor deploy`:

```
Building your app and deploying to host machine -events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at tryNextAuth (/Users/samh/.nvm/versions/node/v6.10.1/lib/node_modules/pm2-meteor/node_modules/ssh2/lib/client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/Users/samh/.nvm/versions/node/v6.10.1/lib/node_modules/pm2-meteor/node_modules/ssh2/lib/client.js:469:5)
    at emitTwo (events.js:106:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (/Users/samh/.nvm/versions/node/v6.10.1/lib/node_modules/pm2-meteor/node_modules/ssh2-streams/lib/ssh.js:3647:10)
    at SSH2Stream._transform (/Users/samh/.nvm/versions/node/v6.10.1/lib/node_modules/pm2-meteor/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/Users/samh/.nvm/versions/node/v6.10.1/lib/node_modules/pm2-meteor/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:334:12)
```
