### ISSUE TITLE
Error: Cannot find module 'fibers'

### ISSUE THREAD

**Issue by dnish** [andruschka/pm2-meteor#16]
When trying to deploy my Meteor 1.3 application, I get this error:

```
elternsachen-web-0 (err): 
    at Function.Module._load (module.js:280:25)

elternsachen-web-0 (err): 
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)

elternsachen-web-0 (err): 
    at Module.require (module.js:364:17)

elternsachen-web-0 (err): 
    at require (module.js:380:17)

elternsachen-web-0 (err): 
    at Object.<anonymous> (/opt/pm2-meteor/elternsachen-web/bundle/programs/server/boot.js:1:75)

elternsachen-web-0 (err): 
    at Module._compile (module.js:456:26)

elternsachen-web-0 (err): 
    at Object.Module._extensions..js (module.js:474:10)

elternsachen-web-0 (err): 
    at Module.load (module.js:356:32)

elternsachen-web-0 (err): 
    at Function.Module._load (module.js:312:12)

elternsachen-web-0 (err): 
Error: Cannot find module 'fibers'

elternsachen-web-0 (err): 
    at Function.Module._resolveFilename (module.js:338:15)

elternsachen-web-0 (err): 
    at Function.Module._load (module.js:280:25)

elternsachen-web-0 (err): 
    at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)

elternsachen-web-0 (err): 
    at Module.require (module.js:364:17)

elternsachen-web-0 (err): 
    at require (module.js:380:17)

elternsachen-web-0 (err): 
    at Object.<anonymous> (/opt/pm2-meteor/elternsachen-web/bundle/programs/server/boot.js:1:75)

elternsachen-web-0 (err): 
    at Module._compile (module.js:456:26)

elternsachen-web-0 (err): 
    at Object.Module._extensions..js (module.js:474:10)

elternsachen-web-0 (err): 
    at Module.load (module.js:356:32)

elternsachen-web-0 (err): 
    at Function.Module._load (module.js:312:12)

```

Any idea what's going wrong?

**Comment by dnish** [comment]
After updating NPM, I'm running into this issue:

```
elternsachen-web-0 Error: /opt/pm2-meteor/elternsachen-web/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node: invalid ELF header
elternsachen-web-0     at Module.load (module.js:356:32)
elternsachen-web-0     at Function.Module._load (module.js:312:12)
elternsachen-web-0     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
elternsachen-web-0     at Module.require (module.js:364:17)
elternsachen-web-0     at require (module.js:380:17)
elternsachen-web-0     at bindings (/opt/pm2-meteor/elternsachen-web/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
elternsachen-web-0     at Object.<anonymous> (/opt/pm2-meteor/elternsachen-web/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
elternsachen-web-0     at Module._compile (module.js:456:26)
elternsachen-web-0     at Object.Module._extensions..js (module.js:474:10)
elternsachen-web-0     at Module.load (module.js:356:32)
```

**Comment by andruschka** [comment]
hmm never experienced an error like that ... more infos would be nice. (Like your pm2-meteor.json) dont forget to censor the passwords ... ^^ We are currently deploying 1.3 apps with no problems...

**Comment by dnish** [comment]
Yeah, we are using Ubuntu 16.04 and deploying via Mac OS. Maybe it has something to do with [this issue?](http://stackoverflow.com/questions/15809611/bcrypt-invalid-elf-header-when-running-node-app)

**Comment by andruschka** [comment]
Ok yes this makes sense - do you pass the right arch flag in the pm2-meteor options ?

**Comment by andruschka** [comment]
e.g. : `"meteorBuildFlags": "--architecture os.linux.x86_64",`

**Comment by dnish** [comment]
Ah, nope, just forget to add this to my config file. This explains the issue :D, thank you.

**Comment by andruschka** [comment]
ok keep me updated about this one !
