### ISSUE TITLE
some confuse about how to start up

### ISSUE THREAD

**Issue by llqgit** [andruschka/pm2-meteor#20]
I have a error when I run **pm2-meteor start**. And I can not find out why. Is there somebody can help me? T^T

```
Starting app on host machine \events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: All configured authentication methods failed
    at tryNextAuth (/usr/local/lib/node_modules/pm2-meteor/node_modules/ssh2/lib/client.js:290:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/usr/local/lib/node_modules/pm2-meteor/node_modules/ssh2/lib/client.js:469:5)
    at emitTwo (events.js:100:13)
    at SSH2Stream.emit (events.js:185:7)
    at parsePacket (/usr/local/lib/node_modules/pm2-meteor/node_modules/ssh2-streams/lib/ssh.js:3647:10)
    at SSH2Stream._transform (/usr/local/lib/node_modules/pm2-meteor/node_modules/ssh2-streams/lib/ssh.js:551:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (/usr/local/lib/node_modules/pm2-meteor/node_modules/ssh2-streams/lib/ssh.js:212:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:300:12)
```

**Comment by andruschka** [comment]
Seems like it cant login to your host machine! I would check your username / pw - or just authenticate with pem file ;)

**Comment by aislanmaia** [comment]
I have the same problem. Using a pem file results in the following error:  "Encrypted private key detected, but no passphrase given"

That's is fixed by [this](https://github.com/arunoda/meteor-up#ssh-keys-with-passphrase-or-ssh-agent-support) from arunoda, but we get the same problem above: "All configured authentication methods failed".

**Comment by allpratik** [comment]
Same issue. Anyone got it resolved?

**Comment by PositronicBrain** [comment]
I have the same problem. Deploying to digital ocean with username and password.

**Comment by MaxTwentythree** [comment]
You could create a ssh key without a passphrase: 
ssh-keygen -t rsa -P '' -f _keyname_
..worked for me

**Comment by llqgit** [comment]
Thanks you guys.
