### ISSUE TITLE
Error after some deploy

### ISSUE THREAD

**Issue by cyclops24** [andruschka/pm2-meteor#40]
Hi @andruschka ,
I can deploy successfully with pm2-meteor but after some modification I try to redeploy my app new version and until then my app completely stoped at all. This is a part of my `pm2-meteor logs` output:
```
0|myapp | 
Error: bind EADDRINUSE 0.0.0.0:4000
0|myapp |     at Object.exports._errnoException (util.js:870:11)
0|myapp |     at exports._exceptionWithHostPort (util.js:893:20)
0|myapp |     at cb (net.js:1302:16)
0|myapp |     at rr (cluster.js:594:14)
0|myapp |     at Worker.<anonymous> (cluster.js:564:9)
0|myapp |     at process.<anonymous> (cluster.js:714:8)
0|myapp |     at emitTwo (events.js:92:20)
0|myapp |     at process.emit (events.js:172:7)

0|myapp |     at handleMessage (internal/child_process.js:689:10)
0|myapp |     at Pipe.channel.onread (internal/child_process.js:440:11)

1|myapp | 
Error: bind EADDRINUSE 0.0.0.0:4000

1|myapp |     at Object.exports._errnoException (util.js:870:11)

1|myapp | 
    at exports._exceptionWithHostPort (util.js:893:20)
1|myapp |     at cb (net.js:1302:16)
1|myapp |     at rr (cluster.js:594:14)
1|myapp |     at Worker.<anonymous> (cluster.js:564:9)
1|myapp |     at process.<anonymous> (cluster.js:714:8)
1|myapp |     at emitTwo (events.js:92:20)

1|myapp |     at process.emit (events.js:172:7)

1|myapp |     at handleMessage (internal/child_process.js:689:10)

1|myapp | 
    at Pipe.channel.onread (internal/child_process.js:440:11)

0|myapp | 
Error: bind EADDRINUSE 0.0.0.0:4000

0|myapp | 
    at Object.exports._errnoException (util.js:870:11)

0|myapp | 
    at exports._exceptionWithHostPort (util.js:893:20)

0|myapp | 
    at cb (net.js:1302:16)

0|myapp | 
    at rr (cluster.js:594:14)

0|myapp | 
    at Worker.<anonymous> (cluster.js:564:9)

0|myapp | 
    at process.<anonymous> (cluster.js:714:8)

0|myapp | 
    at emitTwo (events.js:92:20)

0|myapp | 
    at process.emit (events.js:172:7)

0|myapp | 
    at handleMessage (internal/child_process.js:689:10)

0|myapp | 
    at Pipe.channel.onread (internal/child_process.js:440:11)

1|myapp | Error: bind EADDRINUSE 0.0.0.0:4000

1|myapp |     at Object.exports._errnoException (util.js:870:11)

1|myapp |     at exports._exceptionWithHostPort (util.js:893:20)
1|myapp |     at cb (net.js:1302:16)
1|myapp |     at rr (cluster.js:594:14)
1|myapp |     at Worker.<anonymous> (cluster.js:564:9)
1|myapp |     at process.<anonymous> (cluster.js:714:8)

1|myapp |     at emitTwo (events.js:92:20)
1|myapp |     at process.emit (events.js:172:7)
1|myapp |     at handleMessage (internal/child_process.js:689:10)
1|myapp |     at Pipe.channel.onread (internal/child_process.js:440:11)

0|myapp | 
Error: bind EADDRINUSE 0.0.0.0:4000

0|myapp | 
    at Object.exports._errnoException (util.js:870:11)

0|myapp | 
    at exports._exceptionWithHostPort (util.js:893:20)

0|myapp | 
    at cb (net.js:1302:16)

0|myapp | 
    at rr (cluster.js:594:14)

0|myapp | 
    at Worker.<anonymous> (cluster.js:564:9)

0|myapp | 
    at process.<anonymous> (cluster.js:714:8)

0|myapp | 
    at emitTwo (events.js:92:20)

0|myapp | 
    at process.emit (events.js:172:7)

0|myapp | 
    at handleMessage (internal/child_process.js:689:10)

0|myapp | 
    at Pipe.channel.onread (internal/child_process.js:440:11)

1|myapp | 
Error: bind EADDRINUSE 0.0.0.0:4000

1|myapp |     at Object.exports._errnoException (util.js:870:11)
1|myapp |     at exports._exceptionWithHostPort (util.js:893:20)

1|myapp |     at cb (net.js:1302:16)

1|myapp |     at rr (cluster.js:594:14)
1|myapp |     at Worker.<anonymous> (cluster.js:564:9)
1|myapp | 
    at process.<anonymous> (cluster.js:714:8)

1|myapp | 
    at emitTwo (events.js:92:20)

1|myapp |     at process.emit (events.js:172:7)

1|myapp |     at handleMessage (internal/child_process.js:689:10)

1|myapp | 
    at Pipe.channel.onread (internal/child_process.js:440:11)
```
Is it a issue about pm2 or about pn2-meteor?

**Comment by andruschka** [comment]
Could you log in to your Server and run pm2 list? Seems that it tries to bind to port 4000 but its not possible

**Comment by cyclops24** [comment]
This is `pm2 list` output man:
```
[PM2] Spawning PM2 daemon with pm2_home=/root/.pm2
[PM2] PM2 Successfully daemonized
┌──────────┬────┬──────┬─────┬────────┬─────────┬────────┬─────┬─────┬──────────┐
│ App name │ id │ mode │ pid │ status │ restart │ uptime │ cpu │ mem │ watching │
└──────────┴────┴──────┴─────┴────────┴─────────┴────────┴─────┴─────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```

**Comment by andruschka** [comment]
Ehm did you run it on your server or on your local machine?
Because it seems that you had no applications running... could you run then "pm2-meteor list" in your deployment folder on your local machine?

**Comment by cyclops24** [comment]
Oh man,
I'm sorry.
I have an old deployment with mup on that port and it's running before PM2 when I reboot my server and then port 4000 not accessible for PM2.
I remove that and now all things fixed.

**Comment by cyclops24** [comment]
@andruschka What's `pm2-meteor list` do? I can't see before it in docs or readme of pm2-meteor :thinking:

**Comment by andruschka** [comment]
Oh i meant pm2-Meteor status sorry 😅

**Comment by cyclops24** [comment]
👍 😉
