### ISSUE TITLE
Can't start application

### ISSUE THREAD

**Issue by satyavh** [andruschka/pm2-meteor#44]
Trying this CLI tool out for first time. Started from scratch on new 2 core server (Ubuntu 14.04), following your tutorial. I keep getting errors like this after starting PM2.

(BTW, Do we need all those spaces in the logs? I'd really prefer timestamps!)

```
PM2        | Starting execution sequence in -cluster mode- for app name:main id:0

PM2        | App name:main id:1 online

PM2        | App name:main id:0 online

0|main     | AssertionError: "undefined" === "function"
0|main     |     at wrapPathFunction (/opt/pm2-meteor/bundle/programs/server/mini-files.js:77:10)
0|main     |     at Object.<anonymous> (/opt/pm2-meteor/bundle/programs/server/mini-files.js:108:24)
0|main     |     at Module._compile (module.js:456:26)
0|main     |     at Object.Module._extensions..js (module.js:474:10)
0|main     |     at Module.load (module.js:356:32)
0|main     |     at Function.Module._load (module.js:312:12)
0|main     |     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
0|main     |     at Module.require (module.js:364:17)
0|main     |     at require (module.js:380:17)
0|main     |     at Object.<anonymous> (/opt/pm2-meteor/bundle/programs/server/boot.js:9:13)

PM2        | App name:main id:0 disconnected

PM2        | App [main] with id [0] and pid [31646], exited with code [0] via signal [SIGINT]

PM2        | Script /opt/pm2-meteor/bundle/main.js had too many unstable restarts (16). Stopped. "errored"

1|main     | AssertionError: "undefined" === "function"
1|main     |     at wrapPathFunction (/opt/pm2-meteor/bundle/programs/server/mini-files.js:77:10)
1|main     |     at Object.<anonymous> (/opt/pm2-meteor/bundle/programs/server/mini-files.js:108:24)

1|main     |
    at Module._compile (module.js:456:26)
1|main     |     at Object.Module._extensions..js (module.js:474:10)

1|main     |
    at Module.load (module.js:356:32)
1|main     |
    at Function.Module._load (module.js:312:12)

1|main     |     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)

1|main     |
    at Module.require (module.js:364:17)

1|main     |
    at require (module.js:380:17)

1|main     |
    at Object.<anonymous> (/opt/pm2-meteor/bundle/programs/server/boot.js:9:13)

PM2        |
App name:main id:1 disconnected

PM2        | App [main] with id [1] and pid [31644], exited with code [0] via signal [SIGINT]

PM2        |
Script /opt/pm2-meteor/bundle/main.js had too many unstable restarts (16). Stopped. "errored"
```

my pm2 script:

```
{
  "appName": "myApp",
  "appLocation": {
    "local": "someFolder"
  },
  "meteorSettingsLocation": "someFolder/settings.json",
  "meteorSettingsInRepo": false,
  "meteorBuildFlags": "--architecture os.linux.x86_64",
  "env": {
      "ROOT_URL": "www.somedomain.com",
      "PORT": 3002,
      "MONGO_URL": "Compose Mongo url",
      "MONGO_OPLOG_URL": "Compose Mongo url"
  },
  "server": {
    "host": "51.15.42.133",
    "username": "root",
    "pem":"~/.ssh/scaleway",
    "deploymentDir": "/opt/pm2-meteor",
    "exec_mode": "cluster_mode",
    "instances": 2
  }
}
```

Nginx settings according to your tutorial, except forwarded to port 3002.

**Comment by satyavh** [comment]
I figured it out. I was on old Node version that came with Ubuntu. Right!
