### ISSUE TITLE
Deploying using Gitlab CI and Windows

### ISSUE THREAD

**Issue by erperejildo** [andruschka/pm2-meteor#58]
When I run `pm2-meteor deploy` using Windows I get this error:
```
ERROR: Command failed: C:\Windows\SysWOW64\cmd.exe /s /c "cd C:\Users\Casa\Desktop\food-app\.deploy && tar -zcvf bundle.tar.gz bundle pm2-env.json" "tar" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.
```
And on my pipeline using Gitlab CI this:
```
$ pm2-meteor deploy
Building your app and deploying to host machine
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/usr/local/lib/node_modules/pm2-meteor/node_modules/ssh2/lib/client.js:138:17)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
ERROR: Job failed: exit code 1
```

I don't care about Windows to be honest because I'll use Gitlab CI anyway but I wanted just to let you know

**Comment by erperejildo** [comment]
I don't get that on Gitlab CI always. I tried again and was ok:
`OK: Deployed your app on the host machine!`
