### ISSUE TITLE
app 'errored'

### ISSUE THREAD

**Issue by erperejildo** [andruschka/pm2-meteor#59]
I'm getting this error after deploy. Also I can see 2 apps running when I only run one:
```
recipic@recipic:~$ pm2 list
┌──────────┬────┬─────────┬─────┬─────────┬─────────┬────────┬─────┬────────┬──────────┐
│ App name │ id │ mode    │ pid │ status  │ restart │ uptime │ cpu │ mem    │ watching │
├──────────┼────┼─────────┼─────┼─────────┼─────────┼────────┼─────┼────────┼──────────┤
│ recipic  │ 0  │ cluster │ 0   │ errored │ 105     │ 0      │ 0%  │ 0 B    │ disabled │
│ recipic  │ 1  │ cluster │ 0   │ errored │ 105     │ 0      │ 0%  │ 0 B    │ disabled │
└──────────┴────┴─────────┴─────┴─────────┴─────────┴────────┴─────┴────────┴──────────┘
 Use `pm2 show <id|name>` to get more details about an app
```
I can display these logs:
```
recipic@recipic:~$ pm2 log
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/home/recipic/.pm2/pm2.log last 15 lines:
PM2        | 
PM2        | Error: ENOENT: no such file or directory, uv_cwd
PM2        |     at Object.resolve (path.js:1142:25)
PM2        |     at Function.Module._resolveLookupPaths (module.js:391:17)
PM2        |     at Function.Module._resolveFilename (module.js:461:31)
PM2        |     at Function.Module._load (module.js:418:25)
PM2        |     at Module.require (module.js:498:17)
PM2        |     at require (internal/module.js:20:19)
PM2        |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainer.js:12:15)
PM2        |     at Module._compile (module.js:571:32)
PM2        |     at Object.Module._extensions..js (module.js:580:10)
PM2        |     at Module.load (module.js:488:32)
PM2        | 2017-04-20 15:16:22: App name:recipic id:1 disconnected
PM2        | 2017-04-20 15:16:22: App [recipic] with id [1] and pid [23291], exited with code [1] via signal [SIGINT]
PM2        | 2017-04-20 15:16:22: Script /home/recipic/apps/recipic/bundle/main.js had too many unstable restarts (16). Stopped. "errored"

/home/recipic/.pm2/logs/recipic-out-0.log last 15 lines:
/home/recipic/.pm2/logs/recipic-error-0.log last 15 lines:
/home/recipic/.pm2/logs/recipic-out-1.log last 15 lines:
/home/recipic/.pm2/logs/recipic-error-1.log last 15 lines:
[STREAMING] Now streaming realtime logs for [all] processes
```

If I run my app locally works as expected.

Am I forgetting something maybe?

I'm using Meteor 1.4.2.6 and Ubuntu 16.04

**Comment by erperejildo** [comment]
Tried again and worked

**Comment by adammoisa** [comment]
How did you solve this?

**Comment by adammoisa** [comment]
I have this error:
```
SyntaxError: Unexpected token {
  at exports.runInThisContext (vm.js:53:16)
  at Module._compile (module.js:374:25)
  at Object.Module._extensions..js (module.js:417:10)
  at Module.load (module.js:344:32)
  at Function.Module._load (module.js:301:12)
  at Module.require (module.js:354:17)
  at require (internal/module.js:12:17)
  at Object.<anonymous> (/opt/pm2-meteor/mobile-pos-2-meteor/bundle/main.js:4:1)
  at Module._compile (module.js:410:26)
  at Object.Module._extensions..js (module.js:417:10)
```
