### ISSUE TITLE
How to fixed Error: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by mahadoang** [andruschka/pm2-meteor#84]
"pem": "~/.ssh/id_rsa",

/usr/local/lib/node_modules/pm2-meteor/node_modules/ssh2/lib/client.js:156
      throw new Error('Cannot parse privateKey: ' + privKeyInfo.message);
      ^

Error: Cannot parse privateKey: Unsupported key format
    at Client.connect (/usr/local/lib/node_modules/pm2-meteor/node_modules/ssh2/lib/client.js:156:13)
    at SSH.connect (/usr/local/lib/node_modules/pm2-meteor/node_modules/nodemiral/lib/ssh.js:12:16)
    at Session._withSshClient (/usr/local/lib/node_modules/pm2-meteor/node_modules/nodemiral/lib/session.js:58:12)
    at Session.execute (/usr/local/lib/node_modules/pm2-meteor/node_modules/nodemiral/lib/session.js:140:8)
    at Object.checkDeps (/usr/local/lib/node_modules/pm2-meteor/lib/remoteTasks.js:89:22)
    at /usr/local/lib/node_modules/pm2-meteor/lib/commandList.js:35:30
    at /usr/local/lib/node_modules/pm2-meteor/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/pm2-meteor/node_modules/async/lib/async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (/usr/local/lib/node_modules/pm2-meteor/node_modules/async/lib/async.js:281:9)
    at _parallel (/usr/local/lib/node_modules/pm2-meteor/node_modules/async/lib/async.js:717:9)

**Comment by benbut** [comment]
You can change the type of private key without needing to modify your public key:

`ssh-keygen -m PEM -p -f ~/.ssh/id_rsa`

**Comment by mahadoang** [comment]
@benbut Thank you.
