### ISSUE TITLE
Latest version of pm2-meteor throwing errors

### ISSUE THREAD

**Issue by JackAdams** [andruschka/pm2-meteor#85]
I've updated to the latest version of `pm2-meteor`, trying to deploy a Meteor 1.8.3 app, but I'm getting this for every `pm2-meteor` command I issue in the terminal:
```
$ pm2-meteor deploy
/usr/local/lib/node_modules/pm2-meteor/lib/program.js:11
  ({
   ^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```
Here's the first few lines of the file it refers to:
```
#! /usr/bin/env node
// Generated by CoffeeScript 2.2.4
(function() {
  // cli = require 'cli'
  var cmds, currentVersion, program;

  program = require('commander');

  cmds = require('./commandList');

  ({
    version: currentVersion
  } = require('../package.json'));
```
It's that last line that's causing the error.

Any ideas about what's going on?

**Comment by JackAdams** [comment]
Sorry. My bad. Was running a really old version of node on my mac. Updated it to 8.17.0 and all good now.
